spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profile: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.2.4:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #单机版
  instance: 
    instance-id: microservicecloud-dept8001 #默认服务信息名称修改
    prefer-ip-address: true #显示服务器ip
    
info: 
  app.name: microservicecloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profile: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.2.4:3306/cloudDB02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka #单机版
  instance: 
    instance-id: microservicecloud-dept8001 #默认服务信息名称修改
    prefer-ip-address: true #显示服务器ip
    
info: 
  app.name: microservicecloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$